spring.application.name=avwxora2pg

server.port=${PORT}

spring.output.ansi.enabled=always

# === Oracle DataSource ===
oracle.datasource.url=${ORA_DB_URL}
oracle.datasource.username=${ORA_DB_USERNAME}
oracle.datasource.password=${ORA_DB_PASSWORD}
oracle.datasource.driver-class-name=oracle.jdbc.OracleDriver

# === PostgreSQL DataSource ===
postgres.datasource.url=${PG_DB_URL}
postgres.datasource.username=${PG_DB_USERNAME}
postgres.datasource.password=${PG_DB_PASSWORD}
postgres.datasource.driver-class-name=org.postgresql.Driver

# Actuator
management.endpoints.access.default=none
management.endpoint.health.access=unrestricted
management.endpoint.shutdown.access=unrestricted
management.endpoint.beans.access=unrestricted
management.endpoints.web.exposure.include=health,shutdown,beans
